{
 "title": "retn0's SMARTctl Exporter Dashboard",
 "description": "SMART storage observability dashboard for NVMe/SATA devices via smartctl_exporter and Prometheus.",
 "tags": [
  "smartctl",
  "storage",
  "nvme",
  "sata",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(smartctl_version,instance)"
   },
   {
    "name": "disk",
    "query": "label_values(smartctl_device,device)"
   },
   {
    "name": "type",
    "query": "label_values(smartctl_device,interface)"
   },
   {
    "name": "device_model",
    "query": "label_values(smartctl_device,model_name)"
   },
   {
    "name": "serial_number",
    "query": "label_values(smartctl_device,serial_number)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Monitored Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (max by (instance, device) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(max by (instance, device) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}))) or vector(0)"
    }
   ]
  },
  {
   "title": "Unhealthy Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count((max by (instance, device) (smartctl_device_smart_status{instance=~\"$node\",device=~\"$disk\"} != 1)) and on(instance, device) (max by (instance, device) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))) or vector(0)"
    }
   ]
  },
  {
   "title": "Devices with Critical Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count((max by (instance, device) (smartctl_device_critical_warning{instance=~\"$node\",device=~\"$disk\"} > 0)) and on(instance, device) (max by (instance, device) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))) or vector(0)"
    }
   ]
  },
  {
   "title": "Devices with Media Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count((max by (instance, device) (smartctl_device_media_errors{instance=~\"$node\",device=~\"$disk\"} > 0)) and on(instance, device) (max by (instance, device) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))) or vector(0)"
    }
   ]
  },
  {
   "title": "Devices with Error Logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count((max by (instance, device) (smartctl_device_error_log_count{instance=~\"$node\",device=~\"$disk\"} > 0)) and on(instance, device) (max by (instance, device) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))) or vector(0)"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (instance, device, model_name) (((100 - smartctl_device_percentage_used{instance=~\"$node\",device=~\"$disk\"}) * on(instance, device) group_left(model_name) smartctl_device{interface=~\"$type\",interface=~\"nvme\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})) or max by (instance, device, model_name) ((smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=~\"Percent_Lifetime_Remain|Wear_Leveling_Count|Media_Wearout_Indicator\",attribute_value_type=\"value\"} * on(instance, device) group_left(model_name) smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (instance, device, model_name) (smartctl_device_temperature{instance=~\"$node\",device=~\"$disk\"} * on(instance, device) group_left(model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Temperature Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (instance, device, model_name) (smartctl_device_temperature{instance=~\"$node\",device=~\"$disk\"} * on(instance, device) group_left(model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})",
     "legendFormat": "{{instance}} {{device}} {{model_name}}"
    }
   ]
  },
  {
   "title": "Disk Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_smart_status{instance=~\"$node\",device=~\"$disk\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_critical_warning{instance=~\"$node\",device=~\"$disk\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_media_errors{instance=~\"$node\",device=~\"$disk\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_error_log_count{instance=~\"$node\",device=~\"$disk\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_power_on_seconds{instance=~\"$node\",device=~\"$disk\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_power_cycle_count{instance=~\"$node\",device=~\"$disk\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) (((max by (instance, device) (smartctl_device_bytes_read{instance=~\"$node\",device=~\"$disk\"})) or (max by (instance, device) (smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=\"Total_LBAs_Read\",attribute_value_type=\"raw\"} * on(instance, device) smartctl_device_block_size{instance=~\"$node\",device=~\"$disk\",blocks_type=\"logical\"}))) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) (((max by (instance, device) (smartctl_device_bytes_written{instance=~\"$node\",device=~\"$disk\"})) or (max by (instance, device) (smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=\"Total_LBAs_Written\",attribute_value_type=\"raw\"} * on(instance, device) smartctl_device_block_size{instance=~\"$node\",device=~\"$disk\",blocks_type=\"logical\"}))) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_capacity_bytes{instance=~\"$node\",device=~\"$disk\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{instance=~\"$node\",device=~\"$disk\",interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    }
   ]
  },
  {
   "title": "Power On Hours",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "max by (device) ((smartctl_device_power_on_seconds{instance=~\"$node\",device=~\"$disk\"} / 3600) * on(instance, device) group_left(model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Power Cycles",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (device) (smartctl_device_power_cycle_count{instance=~\"$node\",device=~\"$disk\"} * on(instance, device) group_left(model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Total Reads Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(max by (instance, device, model_name, protocol) (smartctl_device_bytes_read{instance=~\"$node\",device=~\"$disk\"} * on(instance, device) group_left(model_name, protocol) smartctl_device{interface=~\"$type\",interface=~\"nvme\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})) or (max by (instance, device, model_name, protocol) ((smartctl_device_bytes_read{instance=~\"$node\",device=~\"$disk\"}) * on(instance, device) group_left(model_name, protocol) smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) or max by (instance, device, model_name, protocol) ((smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=\"Total_LBAs_Read\",attribute_value_type=\"raw\"} * on(instance, device) smartctl_device_block_size{instance=~\"$node\",device=~\"$disk\",blocks_type=\"logical\"}) * on(instance, device) group_left(model_name, protocol) smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}))",
     "legendFormat": "{{instance}} {{device}} {{model_name}}"
    }
   ]
  },
  {
   "title": "Total Writes Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(max by (instance, device, model_name, protocol) (smartctl_device_bytes_written{instance=~\"$node\",device=~\"$disk\"} * on(instance, device) group_left(model_name, protocol) smartctl_device{interface=~\"$type\",interface=~\"nvme\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})) or (max by (instance, device, model_name, protocol) ((smartctl_device_bytes_written{instance=~\"$node\",device=~\"$disk\"}) * on(instance, device) group_left(model_name, protocol) smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) or max by (instance, device, model_name, protocol) ((smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=\"Total_LBAs_Written\",attribute_value_type=\"raw\"} * on(instance, device) smartctl_device_block_size{instance=~\"$node\",device=~\"$disk\",blocks_type=\"logical\"}) * on(instance, device) group_left(model_name, protocol) smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}))",
     "legendFormat": "{{instance}} {{device}} {{model_name}}"
    }
   ]
  },
  { "title": "NVMe Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Available Spare",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (instance, device, model_name) (smartctl_device_available_spare{instance=~\"$node\",device=~\"$disk\"} * on(instance, device) group_left(model_name) smartctl_device{interface=~\"$type\",interface=~\"nvme\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Spare Threshold",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (instance, device, model_name) (smartctl_device_available_spare_threshold{instance=~\"$node\",device=~\"$disk\"} * on(instance, device) group_left(model_name) smartctl_device{interface=~\"$type\",interface=~\"nvme\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Critical Warnings Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_critical_warning{instance=~\"$node\",device=~\"$disk\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (smartctl_device{interface=~\"$type\",interface=~\"nvme\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}))",
     "legendFormat": "{{instance}} {{device}} {{model_name}}"
    }
   ]
  },
  {
   "title": "Media Errors Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_media_errors{instance=~\"$node\",device=~\"$disk\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (smartctl_device{interface=~\"$type\",interface=~\"nvme\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}))",
     "legendFormat": "{{instance}} {{device}} {{model_name}}"
    }
   ]
  },
  { "title": "SATA Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "SATA Reliability Table",
   "type": "table",
   "description": "SATA fault-focused counters are healthiest at zero, and rising values should be prioritized for investigation.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=\"Current_Pending_Sector\",attribute_value_type=\"raw\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=\"Offline_Uncorrectable\",attribute_value_type=\"raw\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=\"Reallocated_Sector_Ct\",attribute_value_type=\"raw\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=\"Reallocated_Event_Count\",attribute_value_type=\"raw\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=\"UDMA_CRC_Error_Count\",attribute_value_type=\"raw\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (clamp_min(delta(smartctl_device_attribute{instance=~\"$node\",device=~\"$disk\",attribute_name=\"UDMA_CRC_Error_Count\",attribute_value_type=\"raw\"}[24h]), 0))) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    },
    {
     "expr": "max by (instance, device, protocol, model_name, firmware_version, serial_number) ((max by (instance, device) (smartctl_device_error_log_count{instance=~\"$node\",device=~\"$disk\"})) * on(instance, device) group_left(protocol, model_name, firmware_version, serial_number) (max by (instance, device, protocol, model_name, firmware_version, serial_number) (smartctl_device{interface=~\"$type\",interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})))"
    }
   ]
  }
 ]
}