apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: monitoring
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
# Grafana PVC with specific volume name
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "monitoring"
  volumeName: "monitoring-grafana"
